#!/usr/bin/expect -f
#expect script invoqued by ciscobackup to save the configuration of the cisco routers defined at file ~/.ciscorouters
#Jose Antonio Montes 2011

set timeout 10
set server [lindex $argv 0]

set filename [open "~/.ciscorouters" r]
set routers_list [split [read $filename] "\n"]
close $filename

foreach router $routers_list {

	if { $server == [lindex $router 0] } {

		set IP		[lindex $router 2] 
		set user	[lindex $router 3] 
		set password	[lindex $router 4] 
		set enpassword	[lindex $router 5] 
    set isssh [lindex $router 6]

    if { ${isssh} == "ssh" } {

      spawn ssh ${user}@${IP}
      expect {

      "yes/no" {
          send "yes\r"
          exp_continue
        }

      "assword: " { send "$password\r" }

      }

      expect ">"
      send "en\r"
      expect "assword: "
      send "$enpassword\r"

    } else {

                  spawn telnet $IP
                  expect "Username: "
                  send "$user\r"
                  expect "Password: "
                  send "$password\ren\r"
                  expect "Password: "
                  send "$enpassword\r"

    }

    expect "#"
    send "wr t\r"
    expect {

      "More" {
          send " "
          exp_continue
      }
          
      "#" {
          send "exit\r\r"
          exit
      }

    }

	}


}

send_user "The $server doesn\'t exist into the router list\n"
